name: Update readme with Pods

on:
  push:
    paths:
      - 'pods/**'
  pull_request:
    paths:
      - 'pods/**'

# 添加并发控制
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update README
        run: python scripts/update_readme.py

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Pull latest changes
        run: |
          git pull origin main --rebase || git pull origin master --rebase

      - name: Commit and push if changed
        run: |
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with latest pods" && git push) 