name: Update Documentation

on:
  push:
    paths:
      - 'dist/data.json'
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update README and HTML
        run: |
          python scripts/update_readme.py
          python scripts/update_html.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md dist/index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update documentation" && git push) 